### ISSUE TITLE
Changing color of slider arrows

### ISSUE THREAD

**Issue by Galacycy** [opera7133/tella#116]
How do I change the color of the slider arrows on the home page slider ? They are the color white at the moment.

![Screenshot at 2022-09-03 21-51-51](https://user-images.githubusercontent.com/111723274/188297992-82ea5701-e524-48a3-a1d1-e2dd8534eadf.png)

**Comment by opera7133** [comment]
The color of the slider is defined in style.css (style.min.css) as such.
```css
.swiper-button-prev:after,
.swiper-conteiner-rtl,
.swiper-button-next:after {
  color: #fff;
}
.swiper-pagination-bullet {
  background: #fff;
}
```
Since custom.css has the highest priority, you can change the color by changing the value of this and adding it to custom.css.
