### ISSUE TITLE
Instagram icons on features.json not displaying

### ISSUE THREAD

**Issue by pale-bluedot** [opera7133/tella#77]
I'm trying to add social media links with icons on the features.json file. Instagram is not displaying though. I tried other FA5 icons too, but I only see Twitter, FB, and github work. Any ideas?

`[
  {
    "title": "Twitter",
    "description": "Follow us on Twitter",
    "icon": "icon-twitter",
    "link": "https://twitter.com/bikenorthbergen"
  },
  {
    "title": "Instagram",
    "description": "Follow us on Instagram",
    "icon": "icon-instagram",
    "link": "https://www.instagram.com/bikenorthbergen/"
  },
  {
    "title": "Facebook",
    "description": "Follow us on Facebook",
    "icon": "icon-facebook",
    "link": "https://www.facebook.com/Bike-North-Bergen-108227921644201/"
  }
]`

![Image 3](https://user-images.githubusercontent.com/72536144/148719077-03a246d0-9bb3-44cc-ac9c-b6caccb18111.png)

**Comment by opera7133** [comment]
Sorry, the theme does not include instagram icons by default.
Please consider to use FontAwesome.
To use FontAwesome, change to `true` `fa5` of `params.icon`.
Now you can use it like `"icon": "fab fa-instagram"`.

**Comment by pale-bluedot** [comment]
Thank you! I must have used the wrong syntax when I tried fa. On the same topic, is there a parameter for using the icons in [menu.footer] or [menu.main]? I tried:

```
[[menu.footer]]
    icon = "fab fa-twitter"
    url = "https://twitter.com/bikenorthbergen"
    weight = 2
```

**Comment by opera7133** [comment]
Unfortunately, we have not implemented that feature.
We will add the feature when we have time, so if you want to use it, please wait until then.
You can leave this issue open.

**Comment by opera7133** [comment]
Icons can now be used in the footer as well.
You can display the icon by writing the following (The text will not be displayed when the icon is set.)
```toml
[[menu.footer]]
    name = "github"
    pre = "<i class='fab fa-github text-2xl'></i>"
    url = "https://github.com/opera7133/tella"
      weight = 2
```

**Comment by pale-bluedot** [comment]
This works great. Thank you for the update.

One last comment on footer:

I have a parameter with an email in the name:
```
  [[menu.footer]]
   name = "hello@bikenorthbergen.org"
   weight = 1
```

But it is treated like a link for the current page the user is in, instead of just text.
![email](https://user-images.githubusercontent.com/72536144/149844088-193d475e-7c0f-4565-827e-4e4b54ef9bf5.png)
 
Maybe there could be an email parameter that treats it like `mailto` field. Just a thought!

**Comment by opera7133** [comment]
If you need a mailto link, you can specify it in the url parameter.
```toml
[[menu.footer]]
    name = "hello@bikenorthbergen.org"
    url = "mailto:hello@bikenorthbergen.org"
    weight = 1
```
